language: python
python:
    - "2.6"
    - "2.7"
# install dependencies
install:
    - pip install nose
# run tests
script: 
    - nosetests test.testnaga
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then nosetests test.testfinish; fi
